baseURL = "https://www.suhwanshawnkim.com/"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Website of Shawn Kim"
#relativeURLs = true
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

# Localized dates requires Hugo version 0.87.0
localizedDates = false
[params]
title = 'Shawn Kim'
#relativeURLs = true
author = 'Shawn Kim'
description = """
Seasoned Mariners & Seahawks connoisseur 
Pokémon devotee 
Butler of two cats 
Political scientist
REP researcher
"""
institute = "Ph.D. Candidate - Stony Brook Univeristy"
profilePicture = "images/profile.jpg" #"images/lu_su.jpg"
#summary = "Example" #"seasoned Mariners and Seahawks connoisseur, Pokémon devotee, butler of two cats, political scientist"
#favicon = ""
# example ["css/custom.css"]
# customCss = ["/themes/anatole/assets/css/custom.css", "/themes/anatole/assets/css/styles.css"]
# customCss = ["css/custom.css"]
# cstomCss = ["css/styles.css"]
# example ["js/custom.js"]
#customJs = [] 
#mainSections = []
#images = []
doNotLoadAnimations = false
displayMode = "dark"
contentratio = 0.65
# Form Spree Contact Form
#contactFormAction = "https://formspree.io/f/your-form-hash-here"
# Google Site Verify
#googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:suhwan.kim.1@stonybrook.edu"

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "linkedin"
url = "https://www.linkedin.com/in/shawn-suhwan-kim-4011b3a7/"

#[[params.socialIcons]]
#icon = "fab fa-github"
#title = "GitHub"
#url = ""

#[[params.socialIcons]]
#icon = "fab fa-twitter"
#title = "twitter"
#url = ""

#[[params.socialIcons]]
#icon = "fab fa-researchgate"
#title = "researchgate"
#url = ""

## Menu items

[menu]

  [[menu.main]]
  name = "About"
  identifier = "_index"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Research"
  weight = 200
  identifier = "research"
  url = "/research/"

  [[menu.main]]
  name = "Teaching"
  weight = 300
  identifier = "teaching"
  url = "/teaching/"
  
  [[menu.main]]
  name = "CV"
  weight = 400
  identifier = "CV"
  url = "/CV/"  

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"  

[related]
  includeNewer = true
  threshold = 80
  toLower = true
[[related.indices]]
  name = 'keywords'
  weight = 100
[[related.indices]]
  name = 'tags'
  weight = 80  