baseURL = "https://www.suhwanshawnkim.com/"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Website of Shawn Kim"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[params]
title = "Shawn Kim"
author = "Shawn Kim"
description = "PhD Candidate"
institute = "Stony Brook University"
profilePicture = "images/lu_su.jpg"
keywords = ""
favicon = ""
# example ["css/custom.css"]
# customCss = ["/themes/anatole/assets/css/custom.css", "/themes/anatole/assets/css/styles.css"]
# customCss = ["css/custom.css"]
# cstomCss = ["css/styles.css"]
# example ["js/custom.js"]
customJs = [] 
mainSections = []
images = []
doNotLoadAnimations = false
displayMode = "dark"
contentratio = 0.75
# Form Spree Contact Form
#contactFormAction = "https://formspree.io/f/your-form-hash-here"
# Google Site Verify
#googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:suhwan.kim.1@stonybrook.edu"

#[[params.socialIcons]]
#icon = "fab fa-github"
#title = "GitHub"
#url = "https://github.com/peihsunhsieh"

#[[params.socialIcons]]
#icon = "fab fa-twitter"
#title = "twitter"
#url = "https://twitter.com/PeiHsunHsieh"

#[[params.socialIcons]]
#icon = "fab fa-researchgate"
#title = "researchgate"
#url = "https://www.researchgate.net/profile/Pei-Hsun-Hsieh"

## Menu items

[menu]

  [[menu.main]]
  name = "About"
  identifier = "_index"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Research"
  weight = 200
  identifier = "research"
  url = "/research/"

  [[menu.main]]
  name = "Teaching"
  weight = 300
  identifier = "teaching"
  url = "/teaching/"
  
  [[menu.main]]
  name = "CV"
  weight = 400
  identifier = "CV"
  url = "/CV/"  

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"  
