---
title: Bio
date: '2021-05-21'
---

I am a doctoral student at Stony Brook University in the [department of political science](https://www.stonybrook.edu/polsci/). I am primarily interested in behavioral political economy, "the psychologically informed, economic analysis of behavior and its effects in the political arena," as Schnellenbach & Schubert (2015) defined. I use a variety of methods, including experiments, formal modeling, agent-based modeling, and machine learning. In addition, I focus on determining how a person's belief about how others will and should behave shapes decisions in different contexts like redistribution, cooperation, and other political behaviors. I am also the  [Center for Behavioral Political Economy](https://www.stonybrook.edu/commcms/cbpe/) lab manager at Stony Brook University.


## Interests
* Behavioral political economy
* Experimental social science
* Formal and agent-based modeling
* Application of machine learning
* Inequality and redistribution
* Cooperation



<!--
This file is left intentionally empty by default to be backward compatible with initial theme setup.

Although the theme has advanced a little bit and it now allows to specify the content on the main page (even if the list of posts/articles is not intended).
This can be:
- with the list of posts/articles (default: `mainSections = ["post"]) or
- without the list of posts/articles (by setting `mainSections = [""]`)

Markdown supported, ie:

```
# Welcome

- Hugo :rocket:
- Hugo theme :rocket:

Don't forget to check the README.md file!
```

-->
