---
title: CV
author: "Shawn Kim"
date: "12/23/2020"
showtitle: false
---

**You can download pdf file here.**

# Education
Ph.D. in political science, Stony Brook University, Stony Brook, NY, USA  [*2018 \- present*]{style="float:right"}

B.A. in political science, University of Illinois at Urbana-Champaign, Urbana, IL, USA  [*2014 \- 2018*]{style="float:right"}


# Working paper
"(Bounded) Political Friendship? Test of Panethnic Processes for Asians in the US" 

"Political Consequences of Group Norm Exposure"
*With Leonie Huddy*

"Experimental Tests of Self-Reflection on Pro-sociality in Incentivized Contexts"
*With Pei-Hsun Hsieh*

# Additional training
**Summer Institute of Political Psychology (SIPP)** [*2018*]{style="float:right"} <br>
Stanford University
 
# Conference presentation
**2022:**

* MPSA: (Bounded) Political Friendship? Test of Panethnic Processes for Asians in the US

# Fellowships, Grants, and Awards
2020 SPSA Travel Award

# Teaching experience
Instructor, Stony Brook University, U.S.
- American Political Ideology and Public Opinion [*Fall 2021*]{style="float:right"} <br>
- Contemporary Race Relations in American Politics [*Fall 2022*]{style="float:right"} <br>
- Social Networks and Politics [*Fall 2020; Winter 2021; Spring 2021; Summer 2021; Spring 2022; Summer 2022*]{style="float:right"}

# Research and other experience
Research assistant, Department of Political Science, Stony Brook University [*2018 \- 2020*]{style="float:right"} <br>
Supervisor(s): Dr. H. Hannah Nam; Dr. John Barry Ryan; DR. Julian Wamble <br>

Research assistant, Cline Center for Democracy, University of Illinois at Urbana-Champaign [*2017*]{style="float:right"} <br>
Supervisor(s): Dr. Avital Livny <br>

Lab assistant, Department of Political Science, University of Illinois at Urbana-Champaign [*2017*]{style="float:right"} <br>
Supervisor(s): Dr. Aleksander Ksiazkiewicz <br>

Legal intern, Champaign County Public Defender's Office [*2016*]{style="float:right"} <br>
Supervisor(s): Benjamin W. Dyer <br>

Legislative assistant, Assemblywoman Eun-Hee Kwon -- National Assembly of the Republic of Korea [*2015*]{style="float:right"} <br>
Supervisor(s): Yoo-Jung Hong <br>

# Computer Skills
+ **Writing experiment interface:** oTree (Python library)
+ **Data analysis:** R language, Python, Stata, SPSS
